### ISSUE TITLE
Update Staking Contract

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-member-dashboard#144]

**Comment by mikestarrdev** [comment]
Working on it now. I'll also update node to v18, unless there are reasons not to do so

**Comment by mikestarrdev** [comment]
pasting in text from greypixel for reference:

No need to import the lib, update the contract address here: https://github.com/airswap/airswap-voter-rewards/blob/main/src/config/ContractAddresses.ts
The main thing is we need to deal with existing v4 stakers gracefully, they cannot be allowed to partially unstake.

New staked should all go to 4.1 staking
So if someone wants to unstake more than they have in 4.1 but less than they have in 4, we need to handle that. Probably suggest a full v4 unstake plus a partial re stake into 4.1
Migration modal needs to be updated to 4.1.
Open q as to whether we prompt v4 people to migrate to 4.1 but I lean towards nothing intrusive, just a note on the modal that they can only unstake all or nothing
Recommend writing out desired logic in bullet points before code
Possibly warrants a small change to the staking modal with a v4 specific section if the user has a v4 stake

**Comment by mikestarrdev** [comment]
Issue linked to https://github.com/airswap/airswap-voter-rewards/pull/148
